import { DocumentTextIcon, OfficeBuildingIcon } from '@heroicons/react/solid'
import { Preferences } from '../types/Preferences'

const preferences: Preferences = {
  cuisines: [
    { display: 'Any', value: null },
    { display: 'American', value: 'American' },
    { display: 'Asian', value: 'Asian' },
    { display: 'British', value: 'British' },
    { display: 'Caribbean', value: 'Caribbean' },
    { display: 'Central Europe', value: 'Central Europe' },
    { display: 'Chinese', value: 'Chinese' },
    { display: 'Eastern Europe', value: 'Eastern Europe' },
    { display: 'French', value: 'French' },
    { display: 'Indian', value: 'Indian' },
    { display: 'Italian', value: 'Italian' },
    { display: 'Japanese', value: 'Japanese' },
    { display: 'Kosher', value: 'Kosher' },
    { display: 'Mediterranean', value: 'Mediterranean' },
    { display: 'Mexican', value: 'Mexican' },
    { display: 'Middle Eastern', value: 'Middle Eastern' },
    { display: 'Nordic', value: 'Nordic' },
    { display: 'South American', value: 'South American' },
    { display: 'South East Asian', value: 'South East Asian' },
  ],

  diets: [
    { display: 'None', value: null },
    { display: 'Balanced', value: 'balanced' },
    { display: 'High-Fiber', value: 'high-fiber' },
    { display: 'High-Protein', value: 'high-protein' },
    { display: 'Low-Carb', value: 'low-carb' },
    { display: 'Low-Fat', value: 'low-fat' },
    { display: 'Low-Sodium', value: 'low-sodium' },
  ],

  diningOptions: [
    {
      display: 'Recipe',
      value: 'recipe',
      icon: (cn) => <DocumentTextIcon className={cn} />,
    },
    {
      display: 'Restaurant',
      value: 'restaurant',
      icon: (cn) => <OfficeBuildingIcon className={cn} />,
    },
  ],

  mealTypes: [
    { display: 'Any', value: null },
    { display: 'Breakfast', value: 'Breakfast' },
    { display: 'Lunch', value: 'Lunch' },
    { display: 'Dinner', value: 'Dinner' },
    { display: 'Snack', value: 'Snack' },
    { display: 'Teatime', value: 'Teatime' },
  ],

  restrictions: [
    { display: 'None', value: null },
    { display: 'Alcohol-Cocktail', value: 'alcohol-cocktail' },
    { display: 'Alcohol-Free', value: 'alcohol-free' },
    { display: 'Celery-Free', value: 'celery-free' },
    { display: 'Crustcean-Free', value: 'crustacean-free' },
    { display: 'Dairy-Free', value: 'dairy-free' },
    { display: 'DASH', value: 'DASH	Dietary' },
    { display: 'Egg-Free', value: 'egg-free' },
    { display: 'Fish-Free', value: 'fish-free' },
    { display: 'FODMAP-Free', value: 'fodmap-free' },
    { display: 'Gluten-Free', value: 'gluten-free' },
    { display: 'Immuno-Supportive', value: 'immuno-supportive' },
    { display: 'Keto-Friendly', value: 'keto-friendly' },
    { display: 'Kidney-Friendly', value: 'kidney-friendly' },
    { display: 'Kosher', value: 'kosher' },
    { display: 'Low Potassium', value: 'low-potassium' },
    { display: 'Low Sugar', value: 'low-sugar' },
    { display: 'Lupine-Free', value: 'lupine-free' },
    { display: 'Mediterranean', value: 'mediterranean' },
    { display: 'Mollusk-Free', value: 'mollusk-free' },
    { display: 'Mustard-Free', value: 'mustard-free' },
    { display: 'No oil added', value: 'no-oil-added' },
    { display: 'Paleo', value: 'paleo' },
    { display: 'Peanut-Free', value: 'peanut-free' },
    { display: 'Pescatarian', value: 'pecatarian' },
    { display: 'Pork-Free', value: 'pork-free' },
    { display: 'Red-Meat-Free', value: 'red-meat-free' },
    { display: 'Sesame-Free', value: 'sesame-free' },
    { display: 'Shellfish-Free', value: 'shellfish-free' },
    { display: 'Soy-Free', value: 'soy-free' },
    { display: 'Sugar-Conscious', value: 'sugar-conscious' },
    { display: 'Sulfite-Free', value: 'sulfite-free' },
    { display: 'Tree-Nut-Free', value: 'tree-nut-free' },
    { display: 'Vegan', value: 'vegan' },
    { display: 'Vegetarian', value: 'vegetarian' },
    { display: 'Wheat-Free', value: 'wheat-free' },
  ],
}

export default preferences
